### PR TITLE
Plotting domains with and without full metadata.

### PR DESCRIPTION
**Pull request by kbefus**
Some moderate changes to plotting method to allow multiple raster layers
eventually and to add different outline colors based on shp source.
Metadata to populate the popups is a relatively important next step.

### CODE REVIEW

**Comment by rreinecke** [comment]
I will have a look at this tomorrow morning.

**Review by rreinecke — APPROVED** [review]
Great work. You really have been busy. Looks good and I have tested it on my local PC.

It seems though that the paths only work if the app is started from the Gromopo folder. Otherwise the paths relative to the working directory seem to be off.

**Comment by kbefus** [comment]
I had a silly switch in there that helped me work locally vs online, but I had it as a stupid switch based on operating system (where I only let there be Windows for local). A better check to somehow test if it is streamlit hosted or local would be better, but I wasn't sure how to do that. Could also add a list of local operating system options rather than requiring people to be good Windows users.

**Comment by rreinecke** [comment]
Thank you I will create a new issue to track this and maybe change it as some point.

**Pull request merged**
